[workspace]
members = ["cargo:."]

[dist]
cargo-dist-version = "0.30.2"
ci = "github"
installers = ["shell"]
github-attestations = true
targets = ["aarch64-unknown-linux-gnu", "x86_64-unknown-linux-gnu", "x86_64-unknown-linux-musl"]
install-path = "CARGO_HOME"
install-updater = true
include = ["systemd"]
